### ISSUE TITLE
Exclude geekbench? Test less network locations?

### ISSUE THREAD

**Issue by slrslr** [laset-com/speedtest#9]
Hello,

i am having slow VPS. Can i exclude geekbench (hard to understand from https://bench.monster/ if that is possible) and test less network locations (like only 2 US, 2 EU, 2 Asia) or all but with lower amount of test data (VPS having slow network)?

**Comment by laset-com** [comment]
You can run IO test it doen't requare much resouces
`curl -LsO bench.monster/speedtest.sh; bash speedtest.sh -io`
and just a speedtest
`curl -LsO bench.monster/speedtest.sh; bash speedtest.sh -speed`

if you are looking for a lighter or specific location speedtest, use this

```
wget https://raw.githubusercontent.com/laset-com/speedtest-cli/master/speedtest.py
chmod +x speedtest.py
python speedtest.py --server [ID-SERVER]

python speedtest.py --server [ID-SERVER2]

python speedtest.py --server [ID-SERVER3]

...
```
[ID-SERVER] replace with an ID that can be found here https://bench.monster/speedtest.xml

look for XXX inside id="XXX"

**Comment by slrslr** [comment]
i was lost again on https://bench.monster/ trying to find out how to do only speed test.
May be more suggestive if instead of "Global Speedtest" is "Global Speedtest ONLY".

i have used -Asia switch at first and it did all test, then i have tried -as and it did only network test. Seems no intuitive difference between switches and different results.
